# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pop手势返回' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pop手势返回

pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'WRNavigationBar','~>1.0.9'


end
